### ISSUE TITLE
extract_cell_types_mtx.R assumes sample column name is "sample" in a filtering step

### ISSUE THREAD

**Issue by echou89** [EngreitzLab/IGVF_E2G_jamboree_2024#1]
In line 52 of `extract_cell_types_mtx.R`, it attempts to extract the cell type annotations from a column named "sample", which was accounted for in the options list. I edited the code to work like this, which worked for a different column name:

`barcodes_cell_type <- pull(filter(cell_annot, .data[[opt$sample_col]] == cell_type), 1)`

Happy to do a pull request later.

**Comment by argschwind** [comment]
Thanks for catching that! Should be fixed now.
